name: Format and Linter Checks
on:
  - push
  - pull_request
jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Linter
        uses: chartboost/ruff-action@v1
      - name: Format
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"
